apiVersion: v1
kind: ConfigMap
metadata:
    name: mosquitto-password
    namespace: digital-hospitals
    labels:
        app: mosquitto
data:
    password.txt: |
        admin:edit_me_using_mosquitto_passwd
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: mosquitto-config
    namespace: digital-hospitals
data:
    mosquitto.conf: |
        # Config file for mosquitto
        #
        # See mosquitto.conf(5) for more information.
        #
        # Default values are shown, uncomment to change.
        #
        # Use the # character to indicate a comment, but only if it is the
        # very first character on the line.
        listener 1883
        allow_anonymous true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mosquitto-pvc
    namespace: digital-hospitals
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mosquitto
    namespace: digital-hospitals
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mosquitto
    template:
        metadata:
            labels:
                app: mosquitto
        spec:
            volumes:
            -   name: mosquitto-data
                persistentVolumeClaim:
                    claimName: mosquitto-pvc
            -   name: mosquitto-config
                configMap:
                    name: mosquitto-config
            -   name: mosquitto-password
                configMap:
                    name: mosquitto-password
            containers:
            -   name: mosquitto
                image: eclipse-mosquitto:latest
                ports:
                - containerPort: 1883
                volumeMounts:
                -   name: mosquitto-data
                    mountPath: /mosquitto/data
                -   name: mosquitto-config
                    mountPath: /mosquitto/config/mosquitto.conf
                    subPath: mosquitto.conf
                -   name: mosquitto-password
                    mountPath: /mosquitto/config/password.txt
                    subPath: password.txt
                resources:
                    requests:
                        memory: "256Mi"
                        cpu: "250m"
                    limits:
                        memory: "512Mi"
                        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: digital-hospitals
spec:
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: 1883
  selector:
    app: mosquitto